[package]
name = "encryption"
version = "0.1.0"
authors = ["Abraham <cedenoabraham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rsa = "0.4.0"
sha2 = "0.9.5"
base64 = "0.13.0"
wasm-bindgen = "0.2.74"
aes-gcm = "0.9.1"